name: escuelas_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  serverpod_client: 2.1.1
  serverpod_auth_client: 2.1.1
  rolemissions:
    git:
      url: https://github.com/Rodsevich/rolemissions
  escuelas_commons:
    git:
      url: https://github.com/juanjosegarcia98/escuelas_commons
